### ISSUE TITLE
Cannot change the default organization

### ISSUE THREAD

**Issue by lucj** [jp-gouin/helm-openldap#116]
**Describe the bug**

I do not manage to change the default org (from example.org to company.io)

**To Reproduce**

We can reproduce the problem running the chart using the following values.yaml 

```
replicaCount: 1

global:
  ldapDomain: "company.io"
  adminPassword:  Not@SecurePassw0rd
  configPassword: Not@SecurePassw0rd
  ldapPort: 389
  sslLdapPort: 63
```

**Expected behavior**

From the web interface I'd like to connect with `cn=admin,dc=company,dc=io` but it's only possible (using the default password) with `cn=admin,dc=example,dc=org`
