### ISSUE TITLE
Not compatible with Bitnami/openldap 2.6.6

### ISSUE THREAD

**Issue by wynax** [jp-gouin/helm-openldap#136]
Hello,

When i try to update the docker image with bitnami/openldap:2.6.6 it's not working correctly.
The Pod up but the replication is not enable. 

In the log i can see that the {0}module din't create correctly. Bitnami in openldap 2.6.6 add a {0}module with a oclModulePath. In this path the sync module is also not present.

![module](https://github.com/jp-gouin/helm-openldap/assets/32175307/83eb6109-1a14-467a-b066-a6b4056a4ba8)

**Comment by jp-gouin** [comment]
Hi @wynax , 
I created a temporary fix in the upstream container image. 
Can you try using : 
```
image:
  # From repository https://hub.docker.com/r/bitnami/openldap/
  #repository: bitnami/openldap
  #tag: 2.6.3
  # Temporary fix
  repository: jpgouin/openldap
  tag: 2.6.6-fix
```
