### ISSUE TITLE
Install fails on latest chart

### ISSUE THREAD

**Issue by wagnst** [jp-gouin/helm-openldap#14]
**Describe the bug**
Installation fails on K8s `v1.19.7`

**To Reproduce**
```
helm repo add helm-openldap https://jp-gouin.github.io/helm-openldap/
helm --namespace iam upgrade --install openldap helm-openldap/openldap-stack-ha -f values-openldap.yaml
```

**Error message**
`kubectl describe statefulset ...`
```
Events:
  Type     Reason            Age                From                    Message
  ----     ------            ----               ----                    -------
  Normal   SuccessfulCreate  45s                statefulset-controller  create Claim data-openldap-openldap-stack-ha-0 Pod openldap-openldap-stack-ha-0 in StatefulSet openldap-openldap-stack-ha success
  Warning  FailedCreate      4s (x14 over 45s)  statefulset-controller  create Pod openldap-openldap-stack-ha-0 in StatefulSet openldap-openldap-stack-ha failed error: Pod "openldap-openldap-stack-ha-0" is invalid: [spec.volumes[1].secret.secretName: Required value, spec.initContainers[0].volumeMounts[1].name: Not found: "secret-certs"]
```

**Additional context**
`values-openldap.yaml`:
```
env:
 LDAP_ORGANISATION: "redacted"
 LDAP_DOMAIN: "redacted"
 LDAP_READONLY_USER_PASSWORD: "redacted"

service:
  annotations: {} #TODO: set dns record in internal dns
  type: LoadBalancer

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 8Gi  

adminPassword: redacted
configPassword: redacted

ltb-passwd:
  enabled : false

phpldapadmin:
  enabled: false
```
