### ISSUE TITLE
`ldapdelete` when there is no data crashes the pod

### ISSUE THREAD

**Issue by waldner** [jp-gouin/helm-openldap#158]
**Describe the bug**

If I run `ldapdelete -r` after all data has been deleted, the pod crashes (container is terminated with error 139).

**To Reproduce**

```
$ ldapdelete -c -x -r -H ldap://ldap.example.com  -D "cn=admin,dc=om,dc=dsn,dc=example" -w admin  "dc=om,dc=dsn,dc=example"
# works fine, but then:
$ ldapdelete -c -x -r -H ldap://ldap.example.com  -D "cn=admin,dc=om,dc=dsn,dc=example" -w admin  "dc=om,dc=dsn,dc=example"
ldap_search: No such object (32)
ldap_result: Can't contact LDAP server (-1)
```

Looking at `kubectl get pods -n openldap`, I can see that the pod that was hit by the last request has been terminated and is restarting. No error in the logs. From there on, every `ldapdelete` query crashes the pod, unless some data is added to the directory, in which case it can be deleted without errors (but then subsequent deletes cause the pod to crash again, as explained).

**Expected behavior**

Perhaps an error should be returned to the user, but certainly the pod should not crash.

This is an installation with ArgoCD, here is the `Application`:

```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openldap
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://jp-gouin.github.io/helm-openldap
    targetRevision: 4.2.2
    chart: openldap-stack-ha
    helm:
      values: |
        
        global:
          ldapDomain: "dc=om,dc=dsn,dc=example"
          adminUser: admin
          adminPassword: admin
          configUser: admin
          configPassword: admin
        
        replicaCount: 2

        phpldapadmin:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: le-cluster
              cert-manager.io/renew-before: 720h
        
            hosts:
              - ldap-admin.example.com
            tls:
              - secretName: ldap-admin-secret
                hosts:
                  - ldap-admin.example.com
          env:
            PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
        
        ltb-passwd:
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: le-cluster
              cert-manager.io/renew-before: 720h
        
            hosts:
              - ldap-ltb.example.com
            tls:
              - secretName: ldap-ltb-secret
                hosts:
                  - ldap-ltb.example.com
        
        service:
          type: LoadBalancer
          annotations:
            external-dns.alpha.kubernetes.io/hostname: ldap.example.com
        
        persistence:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: openldap
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true

```
