### ISSUE TITLE
Issues bootstrapping `customLdifFiles`

### ISSUE THREAD

**Issue by MartinWeise** [jp-gouin/helm-openldap#175]
**Describe the bug**
I'm trying to add a custom `organizationalUnit` that holds the users and a `groupOfNames` that holds system users. The .ldif looks like this:

```ldif
dn: ou=users,dc=dbrepo,dc=at
objectclass: organizationalUnit
ou: users

dn: cn=system,ou=users,dc=dbrepo,dc=at
objectClass: groupOfNames
cn: system
member: cn=admin,ou=users,dc=dbrepo,dc=at
```

**To Reproduce**
1. Set `global.ldapDomain` to `dbrepo.at`
2. Set `customLdifFiles` as follows:
    ```yaml
    customLdifFiles:
     00-dbrepo.ldif: |-
       version: 1
  
       dn: dc=dbrepo,dc=at
       objectClass: dcObject
       objectClass: organization
       dc: dbrepo
       o: example
       
       dn: ou=users,dc=dbrepo,dc=at
       objectClass: organizationalUnit
       ou: users
       
       dn: cn=system,ou=users,dc=dbrepo,dc=at
       objectClass: groupOfNames
       cn: system
       member: cn=admin,ou=users,dc=dbrepo,dc=at
    ```
3. Connect with the admin credentials on bind dn `cn=admin,dc=dbrepo,dc=at` and see no `organizationalUnit` has been created.

**Expected behavior**
See image below, that both objects are created. When importing the .ldif manually (afterwards) they are created, so they are valid files.

**Screenshots**
![debug](https://github.com/jp-gouin/helm-openldap/assets/2612657/8da80710-494b-425e-9f05-cc0eeb3b2c55)

**Desktop (please complete the following information):**
(not relevant)

**Smartphone (please complete the following information):**
(not relevant)

**Chart version**
4.2.5

**Additional context**
Running on Azure AKS with Kubernetes 1.27.9. I found a similar issue which was resolved: https://github.com/jp-gouin/helm-openldap/issues/46
