### ISSUE TITLE
do_extended: unsupported operation "1.3.6.1.4.1.1466.20037"

### ISSUE THREAD

**Issue by xFiliNx** [jp-gouin/helm-openldap#189]
phpLDAPadmin often returns the error:
```
Failed to start TLS. (openldap.openldap)
Error: Failed to start TLS. Check your LDAP server configuration.
```
At this time, the logs show errors on the openldap-1, openldap-2 pods.
When the service routes traffic through openldap-0, no errors occur.

**Logs**
```
openldap-1 openldap-stack-ha 66aa2e34.3a536b63 0x7f2bddb576c0 conn=1369 op=0 EXT oid=1.3.6.1.4.1.1466.20037                                                                                
openldap-1 openldap-stack-ha 66aa2e34.3a5444fc 0x7f2bddb576c0 conn=1369 op=0 do_extended: unsupported operation "1.3.6.1.4.1.1466.20037"                                                   
openldap-1 openldap-stack-ha 66aa2e34.3a5e2078 0x7f2bd7fff6c0 conn=1370 op=0 EXT oid=1.3.6.1.4.1.1466.20037                                                                                
openldap-1 openldap-stack-ha 66aa2e34.3a5f7873 0x7f2bd7fff6c0 conn=1370 op=0 do_extended: unsupported operation "1.3.6.1.4.1.1466.20037"                                                   
openldap-2 openldap-stack-ha 66aa2e35.3a9bff39 0x7f48bbfff6c0 conn=1376 op=0 EXT oid=1.3.6.1.4.1.1466.20037                                                                                
openldap-2 openldap-stack-ha 66aa2e35.3a9cd12b 0x7f48bbfff6c0 conn=1376 op=0 do_extended: unsupported operation "1.3.6.1.4.1.1466.20037"                                                   
openldap-2 openldap-stack-ha 66aa2e55.254b2451 0x7f48bb7fe6c0 conn=1384 op=0 EXT oid=1.3.6.1.4.1.1466.20037                                                                                
openldap-2 openldap-stack-ha 66aa2e55.254c6aa5 0x7f48bb7fe6c0 conn=1384 op=0 do_extended: unsupported operation "1.3.6.1.4.1.1466.20037"                                                   
openldap-2 openldap-stack-ha 66aa2e55.255bfa41 0x7f48baffd6c0 conn=1385 op=0 EXT oid=1.3.6.1.4.1.1466.20037                                                                                
openldap-2 openldap-stack-ha 66aa2e55.255dac90 0x7f48baffd6c0 conn=1385 op=0 do_extended: unsupported operation "1.3.6.1.4.1.1466.20037"
```
**To Reproduce**
1. Use following values :
```yaml
global:
  ldapDomain: "example.com"
  existingSecret: openldap
clusterDomain: example.com
logLevel: trace
service:
  loadBalancerIP: 192.168.1.1
  type: LoadBalancer
replication:
  enabled: true
  clusterName: "example.com"
containerSecurityContext:
  enabled: true
initTLSSecret:
  tls_enabled: true
  secret: "example.com" 
ltb-passwd:
  ingress:
    ingressClassName: nginx
    hosts:
    - "passwd.example.com"
    tls: 
    - secretName: example.com
      hosts:
      - passwd.example.com
phpldapadmin:
  ingress:
    ingressClassName: nginx
    hosts:
    - ldapadmin.example.com
    tls: 
    - secretName: example.com
      hosts:
      - ldapadmin.example.com
  ```
2. Go to phpldapadmin and refresh the page several times after login
3. See error
