### ISSUE TITLE
customSchema not added on nodes other than first

### ISSUE THREAD

**Issue by Drumar** [jp-gouin/helm-openldap#195]
**Description**
When creating an openldap ha cluster using the helm chart and adding a customSchema, the schema is only added to the first node (openldap-0); openldap-1 and openldap-2 are missing this custom schema. Manually copying this schema to the pv and deleting the pod afterwards will result in a working setup.

**To Reproduce**
Create as normal, add a customSchema, any will do. This schema will only exist on the first node. (you can check the filesystem, the ldif will not exist in openldap-1 and openldap-2

```yaml
customSchemaFiles:
  #enable memberOf ldap search functionality, users automagically track groups they belong to
  00-memberof.ldif: |-
    # Load memberof module
    dn: cn=module,cn=config
    cn: module
    objectClass: olcModuleList
    olcModuleLoad: memberof
    olcModulePath: /opt/bitnami/openldap/lib/openldap

    dn: olcOverlay=memberof,olcDatabase={2}mdb,cn=config
    changetype: add
    objectClass: olcOverlayConfig
    objectClass: olcMemberOf
    olcOverlay: memberof
    olcMemberOfRefint: TRUE
```
(note: I have not tested this schema precisely; I shamelessly copied this one from the advanced examples)

**Expected behavior**
Schema should exist on all nodes.

**Comment by jp-gouin** [comment]
Hi @Drumar can you share your `values` and log of the first init of `openldap-0` ? 

Schema are replicated from the first node to all others

**Comment by Drumar** [comment]
The values:
```yaml
global:
  ldapDomain: dc=example,o=myorg
  adminUser: Manager
  adminPassword: secret
  configUser: admin
  configPassword: config

service:
  annotations: {
      service.beta.kubernetes.io/aws-load-balancer-internal: "true",
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip",
      service.beta.kubernetes.io/aws-load-balancer-subnets: "my-aws-subnet1, my-aws-subnet2, my-aws-subnet3"
    }
  type: LoadBalancer

customSchemaFiles:
  00-anwbSchema.ldif: |-
    dn: cn=myschema,cn=schema,cn=config
    objectClass: olcSchemaConfig
    cn: myschema
    olcAttributeTypes: ( 1.3.6.1.4.1.4203.666.1.50 NAME 'applicationName' SUP commonName )
    olcAttributeTypes: ( 1.3.6.1.4.1.4203.666.1.51 NAME 'myCommonName' SUP commonName )
    olcAttributeTypes: ( 1.3.6.1.4.1.4203.666.1.54 NAME 'mobilePhone' SUP homePhone )
    olcObjectClasses:  ( 2.16.840.1.113730.3.2.3 NAME 'exampleUser' DESC 'Example User' SUP top STRUCTURAL MUST ( uid $ userPassword ) MAY ( cn $ displayName $ givenName $ labeledURI $ mail $ telephoneNumber $ userCertificate $ description ) )
    olcObjectClasses:  ( 1.3.6.1.4.1.4203.666.1.100 NAME 'application' DESC 'Something Special' SUP top STRUCTURAL MUST ( applicationName $ myCommonName $ mobilePhone ) MAY ( description ) )

persistence:
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClass: efs-sc

podSecurityContext:
  enabled: true
  fsGroup: 1001

containerSecurityContext:
  enabled: true
  runAsUser: 1001
  runAsNonRoot: true

volumePermissions:
  enabled: true

phpldapadmin:
  ingress:
    annotations: {
        kubernetes.io/ingress.class: "nginx",
        kubernetes.io/tls-acme: "true"
      }
    ingressClassName: nginx
    path: /phpldapadmin
    hosts:
      - my.real.hostname
```
I do get a lot of errors in the log regarding TLS negiotiation, but discarded that as the data replication seems to work (entries that do not use my schema are replicated) but the problem may reside there; had not expected TLS being required over port 389

The other logs:
`kubectl logs -n openldap openldap-0 init-schema`
This is the main openldap so let's init all additional schemas and ldifs here

`kubectl logs -n openldap openldap-0 init-tls-secret`
```............+++++++++++++++++++++++++++++++++++++++++++++*..+.................+...+.........+...+...+....+...+..+.+......+.....+.+..+.......+......+..+...+...+......+....+.....................+.....+....+..+.......+............+.....+..........+......+..+...+..................+....+......+..+++++++++++++++++++++++++++++++++++++++++++++*...+............+........+....+......+............+...+..+....+...........+.......+..+......+...............+.................................+.+...+..+..........+.....+....+..+...............+.............+.....+......+...+...............+..........+...+..+..........+.....+......+.......+...+.....+......+.............+........+...+.........................+.........+......+..............+.+............+...............+.....+..........+...+...........+......+++++
.........+......+...+.........+..+..........+.........+++++++++++++++++++++++++++++++++++++++++++++*.......+...+...+.....+....+...........+.........+.+..+...............+.+......+...+.................+....+......+.........+......+.....+...+.......+.....+....+..+...+....+...............+......+.....+.......+...+.....+......+................+..+.+.........+...+...............+...+..+...+.........+.+...........+...+.+.....+++++++++++++++++++++++++++++++++++++++++++++*.....+.....+......+.+......+........+.+......+...+......+.....+......+...+.+.....+...............................+..+.+..............+.............+........+....+.....+......................+.....+...+...+.............+.........+.....+...+.......+............+...........+.......+..+....+.....+.+......+..+.+..............+................+...........+...+.......+...........+...............+..................+.+......+.........+...+...+..................+...........+....+.........+......+...............+..+............+.+......+........+......+....+..+.........+.+..............+.......+++++
-----```

The log of volume-permissions is empty; Anything else I can provide?
