### ISSUE TITLE
Can't apply customLdifFiles when enforcing TLS

### ISSUE THREAD

**Issue by Oestle** [jp-gouin/helm-openldap#199]
I'm trying to enforce StartTLS and am running into multiple issues:

- LDAP_TLS_ENFORCE: "true" doesn't seem to do anything
- looking at https://github.com/bitnami/containers/tree/main/bitnami/openldap the correct variable seems to be LDAP_REQUIRE_TLS: "yes", which seems to work, but with it enabled the custom ldifs can't be applied and output the error "text=TLS confidentiality required". 
- trying to enable tls via customSchemaFiles results in the same error and customLdifFiles can't be applied

Current containers vars:
```
    env:
      BITNAMI_DEBUG: "true"
      LDAP_LOGLEVEL: "256"
      LDAP_REQUIRE_TLS: "yes"
      LDAPTLS_REQCERT: "no"
      LDAP_ENABLE_TLS: "yes"
      LDAP_SKIP_DEFAULT_TREE: "yes"
```

With just TLS enabled, but not enforced, everything seems to be working. All the ldifs get applied and i can connect. With the enforcement of TLS the ldifs don't get applied, and hence my tree and users are not created and i can't connect.

Am i missing something or is this broken?
