### ISSUE TITLE
Add more default ENV vars for better out of the box security

### ISSUE THREAD

**Issue by EugenMayer** [jp-gouin/helm-openldap#205]
Considering the bitnami defaults, i would suggest to override and "expose" some of the variable they support. Most of them are not listed on https://hub.docker.com/r/bitnami/openldap

You find a reference on https://github.com/bitnami/containers/blob/main/bitnami/openldap/2.6/debian-12/rootfs/opt/bitnami/scripts/libopenldap.sh

```yaml
env:
  # do not allow non binding by default
  LDAP_ALLOW_ANON_BINDING: no
  # do not create any users by default
  LDAP_USERS: ''
  LDAP_PASSWORDS: ''
  # this is the default, but probably just to be safe (argueable)
  LDAP_CONFIG_ADMIN_ENABLED: no
```

Currently, this charts deploys default users and passwords on all instances, which might be exploited since they are documented. What are your thoughts?

**Comment by EugenMayer** [comment]
Sorry i found https://github.com/jp-gouin/helm-openldap/blob/master/templates/configmap-env.yaml and understood that you already cared about all that, since users/passwords is empty by default (good job).

Leaves us with 

```yaml
env:
  # do not allow non binding by default
  LDAP_ALLOW_ANON_BINDING: no
  # this is the default, but probably just to be safe (argueable)
  LDAP_CONFIG_ADMIN_ENABLED: no
```

What are your thoughs about those?
