### ISSUE TITLE
Support for secret based TLS certificates

### ISSUE THREAD

**Issue by EugenMayer** [jp-gouin/helm-openldap#206]
Any interest in adding customTLS like in here

https://github.com/EugenMayer/helm-openldap/blob/main/templates/statefullset.yaml#L85

i'am using it this way

```yaml
customTLS:
  enabled: true
  secret: ${tls_secret_name}  # The name of a kubernetes.io/tls type secret to use for TLS
  CA:
    # needs ca.crt as field in the secret customTLS.secret
    enabled: true
```

while `tls_secret_name` is just an existing secret. This allows the usual TLS cert way of handling certificates. This is the normalized way of dealing with those certificates in k8s (those can than even be provided by the CertManager`

```yaml
apiVersion: v1
data:
  tls.crt: <cert>
  tls.key: <key>
  ca.crt: <ca.crt>
kind: Secret
metadata:
  name: openldap-tls-secret
  namespace: mynamespace
type: kubernetes.io/tls
```

I could not find anything similar in the chart right now - or i missed it

**Comment by EugenMayer** [comment]
I see, so the one to use with the chart would be

```yaml
initTLSSecret:
  tls_enabled: true
  image:
    registry: docker.io
    repository: alpine/openssl
    tag: latest
    pullPolicy: IfNotPresent
  secret: "custom-cert" 
```

where the secret is the same thing i tried with `customTLS.secret` right?
