### ISSUE TITLE
Feat: Add support for cert-manager 

### ISSUE THREAD

**Issue by jp-gouin** [jp-gouin/helm-openldap#210]
**Is your feature request related to a problem? Please describe.**
For production environment , it's best to verify the certificate during the replication between each nodes. Currently this is only possible by bringing our own certificate. 

**Describe the solution you'd like**
Add a certificate resource for cert-manager support. Need to input the `issuerRef`. 
`dnsNames` can be computed automatically using the services name, headless + replica count 

The value could look like : 
```
initTLSSecret:
...
  certManager: 
    issuerRef:
        name: selfsigned-ca
        kind: Issuer
```

(Feel free to upvote it, so I can get a sense at how useful it can be :) )
