### ISSUE TITLE
Question: ACLs are not working - or i configured them the wrong way?

### ISSUE THREAD

**Issue by EugenMayer** [jp-gouin/helm-openldap#211]
I do deploy custom ACLs to have the ability to

1. let every user maintain there password
2. let the admin do anything
3. create a read-only user that can read everythin

So i did

```yaml
customAcls: |-
  dn: olcDatabase={2}mdb,cn=config
  changetype: modify
  replace: olcAccess
  olcAccess: {0}to *
    by dn="cn=readonly,ou=users,dc=example,dc=com" read
    by dn="cn=readonly,dc=example,dc=com" read
    by dn="cn=admin,dc=example,dc=com" write
    by * none
  olcAccess: {1}to attrs=userPassword,shadowLastChange
    by self write
    by dn="cn=admin,dc=example,dc=com" write
    by anonymous auth by * none
```

Now, i can connect with the admin user and i can see the entire tree (and edit).

While connecting with the readoly user does work, i cannot see any entries at all. I'am aware of https://github.com/jp-gouin/helm-openldap/issues/115 and the issue of bitnami that all of this is not applied after the first bootstrap - so i only test this with initial bootstrap (with the same result).

Any hints what i do wrong or how to validate that those ACLs have been applied at all?

**Comment by EugenMayer** [comment]
Checking the boostrap, i cannot see any log about customACLs bing applied - nothing about ACLs. I see that those are immplemented with https://github.com/jp-gouin/helm-openldap/blob/8fd04c4e3fe23e6f497416052fc4db06f522db49/templates/configmap-replication-acls.yaml#L66 and via https://github.com/jp-gouin/helm-openldap/blob/8fd04c4e3fe23e6f497416052fc4db06f522db49/templates/statefulset.yaml#L94  in the `init-schema` container

but the only log i see is in the `init-schema`  is

```
This is the main openldap so let's init all additional schemas and ldifs here
```

I checked the config map `openldap-replication-acls` and und acls.ldif i see my ACL defintions at least

**Comment by EugenMayer** [comment]
I enriched my setup to add schemas and custom ldifs

```yaml
customLdifFiles:
  00-root.ldif: |-
    dn: dc=example,dc=com
    objectClass: top
    objectClass: dcObject
    objectClass: organization
    o: example
    dc: example
  01-readonly.ldif: |-
    dn: cn=readonly,dc=example,dc=com
    objectClass: organizationalRole
    objectClass: simpleSecurityObject
    cn: readonly
    userPassword:: {SSHA}NBhpOZsabcczdass23dJglApn/ 
    description: LDAP read only user
  03-test-memberof.ldif: |-
    dn: ou=Group,dc=example,dc=org
    objectclass: organizationalUnit
    ou: Group
    
    dn: ou=People,dc=example,dc=org
    objectclass: organizationalUnit
    ou: People
    
    dn: uid=test1,ou=People,dc=example,dc=org
    objectclass: account
    uid: test1
    
    dn: cn=testgroup,ou=Group,dc=example,dc=org
    objectclass: groupOfNames
    cn: testgroup
    member: uid=test1,ou=People,dc=example,dc=org
customSchemaFiles:
  memberof.ldif: |-
    dn: cn=module,cn=config
    cn: module
    objectClass: olcModuleList
    olcModuleLoad: memberof
    olcmoduleload: refint
    olcModulePath: /opt/bitnami/openldap/lib/openldap
    
    #memberof overlay
    dn: olcOverlay=memberof,olcDatabase={2}mdb,cn=config
    objectClass: olcMemberOf
    objectClass: olcOverlayConfig
    objectClass: olcConfig
    objectClass: top
    olcOverlay: memberof
    olcMemberOfDangling: ignore
    olcMemberOfRefInt: TRUE
    olcMemberOfGroupOC: groupOfUniqueNames
    olcMemberOfMemberAD: uniqueMember
    olcMemberOfMemberOfAD: memberOf
    
    #refint overlay
    dn: olcOverlay=refint,olcDatabase={2}mdb,cn=config
    objectClass: olcOverlayConfig
    objectClass: olcRefintConfig
    olcOverlay: refint
    olcRefintAttribute: owner
    olcRefintAttribute: manager
    olcRefintAttribute: uniqueMember
    olcRefintAttribute: member
    olcRefintAttribute: memberOf

customAcls: |-
  dn: olcDatabase={2}mdb,cn=config
  changetype: modify
  replace: olcAccess
  olcAccess: {0}to *
    by dn.exact=gidNumber=0+uidNumber=1001,cn=peercred,cn=external,cn=auth manage
    by * break
  olcAccess: {1}to attrs=userPassword,shadowLastChange
    by self write
    by dn="cn=admin,dc=example,dc=com" write
    by anonymous auth by * none
  olcAccess: {2}to *
    by dn="cn=readonly,ou=users,dc=example,dc=com" read
    by dn="cn=readonly,dc=example,dc=com" read
    by dn="cn=admin,dc=example,dc=com" write
    by self read
    by * none
```

Neither of these things have actually been created.

It is hard to debug what the cause might be since  https://github.com/jp-gouin/helm-openldap/blob/master/templates/statefulset.yaml#L55 is fairly "silent" - i would suggest adding `-v` there so everybody can see the logs in the init container.

Nevertheless neither the users, groups nor anything else have been created and i currently cannot understand how this is supposed to work right now. The bitnami image does not support either of this folders out of the box:

- /custom-schemas/
- /custom-ldifs/
- /custom_config/

Still, all the init container does is copy files into that folder, on those mounts are later not used for the actual image anyway. So how is this supposed to work, i assume i missed something?
