### ISSUE TITLE
using initTLSSecret still provides the self-signed certificate

### ISSUE THREAD

**Issue by EugenMayer** [jp-gouin/helm-openldap#214]
Trying to deploy a custom / official certificate

```yaml
initTLSSecret:
  enabled: true
  secret: openldap-tls-secret
```

```hcl
resource "kubernetes_secret" "cert" {
  metadata {
    name      = local.tls_secret_name
    namespace = module.hardened_namespace.namespace.id
  }
  binary_data = {
    "ca.crt" = "base64 censored"
    "tls.crt"  = "base64 censored"
    "tls.key" = var.tls_key
  }
}
```

It is deployed, checking the values looks good too
![image](https://github.com/user-attachments/assets/f767d1e3-1878-4943-99f3-8cee61d22362)

After re-deploying (fresh deployment) the chart, i still get greeted with the self-signed certifate.

**Comment by EugenMayer** [comment]
Rubber ducked myself .. sorry, after tripple checking for this issue if found out its

```yaml
initTLSSecret:
  tls_enabled: true
  secret: openldap-tls-secret
```

not 

```yaml
initTLSSecret:
  enabled: true
  secret: openldap-tls-secret
```

even though `tls_enabled` is fairly suprising (compared to all the others), still it is well documented - so my own fault for sure.
