### ISSUE TITLE
confusing values entry:  logLevel

### ISSUE THREAD

**Issue by ShamrockOo4tune** [jp-gouin/helm-openldap#216]
**Describe the bug**
values entry: `logLevel`, specifically switching it  to  debug` does not have any effect and brings confusion to the chart users

**To Reproduce**
1. Use following values :
  ```yaml
  
  ...
  logLevel: debug
  ...
  env:
    # LDAP_LOGLEVEL: "256"
  ...
  
  ```
2. Go execute any query
3. See logs

**Expected behavior**
Expected effect: same as when changing log level with  LDAP_LOGLEVEL environment variable 

**Additional context**
looks like e648cf3 has removed this functionality
