### ISSUE TITLE
failed with: Back-off restarting failed container init-tls-secret

### ISSUE THREAD

**Issue by lordk911** [jp-gouin/helm-openldap#218]
**Describe the bug**
helm chart version: 4.3.1, container openldap-0 can not start up 

```
kubectl get all -n openldap
NAME             READY   STATUS                  RESTARTS        AGE
pod/openldap-0   0/1     Init:CrashLoopBackOff   9 (2m39s ago)   23m

NAME                        TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)           AGE
service/openldap            ClusterIP   10.96.3.65   <none>        389/TCP,636/TCP   23m
service/openldap-headless   ClusterIP   None         <none>        389/TCP,636/TCP   23m

NAME                        READY   AGE
statefulset.apps/openldap   0/3     23m

NAME                                                                            AGE
componentresourceconstraint.apps.kubeblocks.io/kb-resource-constraint-general   256d
```

```
docker images | grep openssl
sealos.hub:5000/alpine/openssl                                                  latest                                      74e221540a52   4 days ago      15.8MB

```

```
kubectl describe pod/openldap-0 -n openldap
Name:             openldap-0
Namespace:        openldap
Priority:         0
Service Account:  openldap-openldap-stack-ha-foo
Node:             x2726.seal.xa/10.9.27.26
Start Time:       Wed, 13 Nov 2024 16:12:16 +0800
Labels:           app.kubernetes.io/component=openldap
                  app.kubernetes.io/instance=openldap
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=openldap-stack-ha
                  app.kubernetes.io/version=2.6.7
                  controller-revision-hash=openldap-f569798bc
                  helm.sh/chart=openldap-stack-ha-4.3.1
                  release=openldap
                  statefulset.kubernetes.io/pod-name=openldap-0
Annotations:      checksum/configmap-env: 14d176661e7070d8939a7fb887f7961a71396c7fd266c62d697eab8088d16dd3
Status:           Pending
IP:               10.0.2.190
IPs:
  IP:           10.0.2.190
Controlled By:  StatefulSet/openldap
Init Containers:
  init-schema:
    Container ID:  docker://25410498d9a04ea14b8b48ab33da082ba93cd62089f2a43537633cb9ac9f53dc
    Image:         debian:latest
    Image ID:      docker-pullable://debian@sha256:10901ccd8d249047f9761845b4594f121edef079cfd8224edebd9ea726f0a7f6
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      host=$(hostname)
      if [ "$host" = "openldap-0" ]
      then
        echo "This is the main openldap so let's init all additional schemas and ldifs here"
        cp -p -f /cm-schemas-acls/*.ldif /custom_config/
        if [ -d /cm-schemas ]; then
          cp -p -f /cm-schemas/*.ldif /custom-schemas/
        fi
        if [ -d /cm-ldifs ]; then
          cp -p -f /cm-ldifs/*.ldif /custom-ldifs/
        fi
      else
        cp -p -f /cm-schemas-acls/*.ldif /custom_config/
        echo "let the replication takes care of everything :)"
      fi
      
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Wed, 13 Nov 2024 16:12:17 +0800
      Finished:     Wed, 13 Nov 2024 16:12:17 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /cm-schemas-acls from cm-replication-acls (rw)
      /custom_config from replication-acls (rw)
  init-tls-secret:
    Container ID:  docker://1bbcae7765c9384d3d1bf4f27f462f217778e95ca7ec4055b2ef81362deceaee
    Image:         sealos.hub:5000/alpine/openssl:latest
    Image ID:      docker-pullable://sealos.hub:5000/alpine/openssl@sha256:bbe0b0fa614be7d8f180b29422b4a468ed956d1234aff5f1c237a3e421717671
    Port:          <none>
    Host Port:     <none>
    Command:
      sh
      -c
      openssl req -x509 -newkey rsa:4096 -nodes -subj '/CN=example.org' -keyout /tmp-certs/tls.key -out /tmp-certs/tls.crt -days 365
      chmod 777  /tmp-certs/*
      cp -Lr /tmp-certs/* /certs
      [ -e /certs/ca.crt ] || cp -a /certs/tls.crt /certs/ca.crt
      
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 13 Nov 2024 16:38:23 +0800
      Finished:     Wed, 13 Nov 2024 16:38:23 +0800
    Ready:          False
    Restart Count:  10
    Environment:    <none>
    Mounts:
      /certs from certs (rw)
      /tmp-certs from secret-certs (rw)

```

**Logs**
```
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  17m                   default-scheduler  Successfully assigned openldap/openldap-0 to x2726.seal.xa
  Normal   Pulled     17m                   kubelet            Container image "debian:latest" already present on machine
  Normal   Created    17m                   kubelet            Created container init-schema
  Normal   Started    17m                   kubelet            Started container init-schema
  Normal   Pulled     16m (x5 over 17m)     kubelet            Container image "sealos.hub:5000/alpine/openssl:latest" already present on machine
  Normal   Created    16m (x5 over 17m)     kubelet            Created container init-tls-secret
  Normal   Started    16m (x5 over 17m)     kubelet            Started container init-tls-secret
  Warning  BackOff    2m45s (x70 over 17m)  kubelet            Back-off restarting failed container init-tls-secret in pod openldap-0_openldap(3c47e82e-f515-4a57-a86d-beb71bbfcf69)
```

*Hint* you can use `kubectl logs <pod_name> --previous` to get the log of the previous execution of the pod

**To Reproduce**
1. Use following values :
  ```yaml
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  #imagePullSecrets: [""]
  ## ldapDomain , can be explicit (e.g dc=toto,c=ca) or domain based (e.g example.com)
  ldapDomain: "example.org"
  # Specifies an existing secret to be used for admin and config user passwords. The expected key are LDAP_ADMIN_PASSWORD and LDAP_CONFIG_ADMIN_PASSWORD.
  # existingSecret: ""
  ## Default Passwords to use, stored as a secret. Not used if existingSecret is set.
  adminUser: "admin"
  adminPassword: Not@SecurePassw0rd
  configUser: "admin"
  configPassword: Not@SecurePassw0rd
  ldapPort: 389
  sslLdapPort: 636

## @section Common parameters

## @param kubeVersion Override Kubernetes version
##
kubeVersion: ""
## @param nameOverride String to partially override common.names.fullname
##
nameOverride: ""
## @param fullnameOverride String to fully override common.names.fullname
##
fullnameOverride: ""
## @param commonLabels Labels to add to all deployed objects
##
commonLabels: {}
## @param commonAnnotations Annotations to add to all deployed objects
##
commonAnnotations: {}
## @param clusterDomain Kubernetes cluster domain name
##
clusterDomain: cluster.local
## @param extraDeploy Array of extra objects to deploy with the release
##
extraDeploy: []

replicaCount: 3

# Note: you need replication enabled to use readonly replicas!
readOnlyReplicaCount: 0

image:
  # From repository https://hub.docker.com/r/bitnami/openldap/
  #repository: bitnami/openldap
  #tag: 2.6.3
  # Temporary fix
  registry: sealos.hub:5000
  repository: jpgouin/openldap
  tag: 2.6.8-fix
  pullPolicy: IfNotPresent
  pullSecrets: []

# Set the container log level
# Valid log levels: none, error, warning, info (default), debug, trace
logLevel: info

initSchema:
  image: 
    repository: debian
    tag: latest
    pullPolicy: IfNotPresent
    pullSecrets: []

extraLabels: {}

service:
  annotations: {}
  ## If service type NodePort, define the value here
  #ldapPortNodePort:
  #sslLdapPortNodePort:

  # Disable if you do not want to expose port on service
  enableLdapPort: true
  enableSslLdapPort: true

  ## List of IP addresses at which the service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  ## Define a static clusterIP
  #clusterIP:
  #loadBalancerIP:
  #loadBalancerSourceRanges: []
  type: ClusterIP
  sessionAffinity: None

  ## Represents the dual-stack-ness requested or required by this Service. Possible values are
  ## SingleStack, PreferDualStack or RequireDualStack.
  ## The ipFamilies and clusterIPs fields depend on the value of this field.
  ## Ref: https://kubernetes.io/docs/concepts/services-networking/dual-stack/
  ipFamilyPolicy: SingleStack

# Service for read only cluster pods (if enabled)
serviceReadOnly:
  annotations: {}
  ## If service type NodePort, define the value here
  #ldapPortNodePort:
  #sslLdapPortNodePort:

  # Disable if you do not want to expose port on service
  enableLdapPort: true
  enableSslLdapPort: true

  # Control ports used in statefulset
  headlessEnableLdapPort: true
  headlessEnableSslLdapPort: true

  ## List of IP addresses at which the service is available
  ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
  ##
  externalIPs: []

  ## Define a static clusterIP
  #clusterIP:
  #loadBalancerIP:
  #loadBalancerSourceRanges: []
  type: ClusterIP
  sessionAffinity: None

  ## Represents the dual-stack-ness requested or required by this Service. Possible values are
  ## SingleStack, PreferDualStack or RequireDualStack.
  ## The ipFamilies and clusterIPs fields depend on the value of this field.
  ## Ref: https://kubernetes.io/docs/concepts/services-networking/dual-stack/
  ipFamilyPolicy: SingleStack

# Default configuration for openldap as environment variables. These get injected directly in the container.
# Use the env variables from https://hub.docker.com/r/bitnami/openldap/
# Be careful, do not modify the following values unless you know exactly what your are doing
env:
 BITNAMI_DEBUG: "true"
 LDAP_LOGLEVEL: "256"
 LDAP_REQUIRE_TLS: "false"
 LDAPTLS_REQCERT: "never"
 LDAP_ENABLE_TLS: "yes"
 LDAP_SKIP_DEFAULT_TREE: "no"


# Pod Disruption Budget for Stateful Set
# Disabled by default, to ensure backwards compatibility
pdb:
  enabled: false
  minAvailable: 1
  maxUnavailable: ""

replication:
  enabled: true
  # Enter the name of your cluster, defaults to "cluster.local"
  clusterName: "cluster.local"
  retry: 60
  timeout: 1
  interval: 00:00:00:10
  starttls: "critical"
  # override the tls_reqcert parameter (default if never and demand when initTLSSecret.tls_enabled = true )
  # tls_reqcert: "never"
  # override the location of tls_cacert to trust (allowed when initTLSSecret.tls_enabled = true )
  # tls_cacert: "/etc/ssl/certs/ca-certificates.crt"
## Persist data to a persistent volume
persistence:
  enabled: true
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "standard-singlewriter"
  # existingClaim: openldap-pvc
  accessModes:
    - ReadWriteOnce
  size: 8Gi
  storageClass: ""

## @param customLivenessProbe Custom livenessProbe that overrides the default one
##
customLivenessProbe: {}
## @param customReadinessProbe Custom readinessProbe that overrides the default one
##
customReadinessProbe: {}
## @param customStartupProbe Custom startupProbe that overrides the default one
##
customStartupProbe: {}
## OPENLDAP  resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
## @param resources.limits The resources limits for the OPENLDAP  containers
## @param resources.requests The requested resources for the OPENLDAP  containers
##
resources:
  limits: {}
  requests: {}
## Configure Pods Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
## @param podSecurityContext.enabled Enabled OPENLDAP  pods' Security Context
## @param podSecurityContext.fsGroup Set OPENLDAP  pod's Security Context fsGroup
##
podSecurityContext:
  enabled: true
  fsGroup: 1001
## Configure Container Security Context
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod
## @param containerSecurityContext.enabled Enabled OPENLDAP  containers' Security Context
## @param containerSecurityContext.runAsUser Set OPENLDAP  containers' Security Context runAsUser
## @param containerSecurityContext.runAsNonRoot Set OPENLDAP  containers' Security Context runAsNonRoot
##
containerSecurityContext:
  enabled: false
  runAsUser: 1001
  runAsNonRoot: true

## @param existingConfigmap The name of an existing ConfigMap with your custom configuration for OPENLDAP
##
existingConfigmap:
## @param command Override default container command (useful when using custom images)
##
command: []
## @param args Override default container args (useful when using custom images)
##
args: []
## @param hostAliases OPENLDAP  pods host aliases
## https://kubernetes.io/docs/concepts/services-networking/add-entries-to-pod-etc-hosts-with-host-aliases/
##
hostAliases: []
## @param podLabels Extra labels for OPENLDAP  pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/
##
podLabels: {}
## @param podAnnotations Annotations for OPENLDAP  pods
## ref: https://kubernetes.io/docs/concepts/overview/working-with-objects/annotations/
##
podAnnotations: {}
## @param podAffinityPreset Pod affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
##
podAffinityPreset: ""
## @param podAntiAffinityPreset Pod anti-affinity preset. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
##
podAntiAffinityPreset: soft
## Node affinity preset
## ref: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
##
nodeAffinityPreset:
  ## @param nodeAffinityPreset.type Node affinity preset type. Ignored if `affinity` is set. Allowed values: `soft` or `hard`
  ##
  type: ""
  ## @param nodeAffinityPreset.key Node label key to match. Ignored if `affinity` is set
  ##
  key: ""
  ## @param nodeAffinityPreset.values Node label values to match. Ignored if `affinity` is set
  ## E.g.
  ## values:
  ##   - e2e-az1
  ##   - e2e-az2
  ##
  values: []
## @param affinity Affinity for OPENLDAP  pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
## NOTE: `podAffinityPreset`, `podAntiAffinityPreset`, and `nodeAffinityPreset` will be ignored when it's set
##
affinity: {}
## @param nodeSelector Node labels for OPENLDAP  pods assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
##
nodeSelector: {}
## @param tolerations Tolerations for OPENLDAP  pods assignment
## ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
## @param updateStrategy.type OPENLDAP  statefulset strategy type
## ref: https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#update-strategies
##
updateStrategy:
  ## StrategyType
  ## Can be set to RollingUpdate or OnDelete
  ##
  type: RollingUpdate
## @param priorityClassName OPENLDAP  pods' priorityClassName
##
priorityClassName: ""
## @param schedulerName Name of the k8s scheduler (other than default) for OPENLDAP  pods
## ref: https://kubernetes.io/docs/tasks/administer-cluster/configure-multiple-schedulers/
##
schedulerName: ""
## @param lifecycleHooks for the OPENLDAP  container(s) to automate configuration before or after startup
##
lifecycleHooks: {}
## @param extraEnvVars Array with extra environment variables to add to OPENLDAP  nodes
## e.g:
## extraEnvVars:
##   - name: FOO
##     value: "bar"
##
extraEnvVars: []
## @param extraEnvVarsCM Name of existing ConfigMap containing extra env vars for OPENLDAP  nodes
##
extraEnvVarsCM:
## @param extraEnvVarsSecret Name of existing Secret containing extra env vars for OPENLDAP  nodes
##
extraEnvVarsSecret:
## @param extraVolumes Optionally specify extra list of additional volumes for the OPENLDAP  pod(s)
##
extraVolumes: []
## @param extraVolumeMounts Optionally specify extra list of additional volumeMounts for the OPENLDAP  container(s)
##
extraVolumeMounts: []
## @param sidecars Add additional sidecar containers to the OPENLDAP  pod(s)
## e.g:
## sidecars:
##   - name: your-image-name
##     image: your-image
##     imagePullPolicy: Always
##     ports:
##       - name: portname
##         containerPort: 1234
##
sidecars: {}
## @param initContainers Add additional init containers to the OPENLDAP  pod(s)
## ref: https://kubernetes.io/docs/concepts/workloads/pods/init-containers/
## e.g:
## initContainers:
##  - name: your-image-name
##    image: your-image
##    imagePullPolicy: Always
##    command: ['sh', '-c', 'echo "hello world"']
##
initContainers: {}

## Service Account
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/
##
serviceAccount:
  ## @param serviceAccount.create Enable creation of ServiceAccount for Apache pod
  ##
  create: true
  ## @param serviceAccount.name The name of the ServiceAccount to use.
  ## If not set and create is true, a name is generated using the common.names.fullname template
  ##
  name: ""
  ## @param serviceAccount.automountServiceAccountToken Allows auto mount of ServiceAccountToken on the serviceAccount created
  ## Can be set to false if pods using this serviceAccount do not need to use K8s API
  ##
  automountServiceAccountToken: false
  ## @param serviceAccount.annotations Additional custom annotations for the ServiceAccount
  ##
  annotations: {}  

## @section Init Container Parameters

## 'initTlsSecret' init container parameters
## need a secret with tls.crt, tls.key and ca.crt keys with associated files
## based on the *containerSecurityContext parameters
##
initTLSSecret:
  tls_enabled: false
  ##  openssl image
  ## @param initTlsSecret.image.registry openssl image registry
  ## @param initTlsSecret.image.repository openssl image name
  ## @param initTlsSecret.image.tag openssl image tag
  ##
  image:
    registry: sealos.hub:5000
    repository: alpine/openssl
    tag: latest
    ## @param image.pullPolicy openssl image pull policy
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: https://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: IfNotPresent
  # The name of a kubernetes.io/tls type secret to use for TLS
  secret: "" 
  ## init-tls-secret container's resource requests and limits
  ## ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  ## @param initTlsSecret.resources.limits The resources limits for the init container
  ## @param initTlsSecret.resources.requests The requested resources for the init container
  ##
  resources:
    ## Example:
    ## limits:
    ##   cpu: 500m
    ##   memory: 1Gi
    limits: {}
    requests: {}

## 'volumePermissions' init container parameters
## Changes the owner and group of the persistent volume mount point to runAsUser:fsGroup values
##   based on the *podSecurityContext/*containerSecurityContext parameters
##
volumePermissions:
  ## @param volumePermissions.enabled Enable init container that changes the owner/group of the PV mount point to `runAsUser:fsGroup`
  ##
  enabled: false
  ## Bitnami Shell image
  ## ref: https://hub.docker.com/r/bitnami/bitnami-shell/tags/
  ## @param volumePermissions.image.registry Bitnami Shell image registry
  ## @param volumePermissions.image.repository Bitnami Shell image repository
  ## @param volumePermissions.image.tag Bitnami Shell image tag (immutable tags are recommended)
  ## @param volumePermissions.image.pullPolicy Bitnami Shell image pull policy
  ##
  image:
    registry: docker.io
    repository: bitnami/bitnami-shell
    tag: 10-debian-10
    pullPolicy: IfNotPresent

  ## Command to execute during the volumePermission startup
    command: [ 'sh', '-c', 'chmod -R g+rwX /bitnami' ]
  ## command: {}
  ## Init container's resource requests and limits
  ## ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  ## @param volumePermissions.resources.limits The resources limits for the init container
  ## @param volumePermissions.resources.requests The requested resources for the init container
  ##
  resources:
    ## Example:
    ## limits:
    ##   cpu: 500m
    ##   memory: 1Gi
    limits: {}
    requests: {}

## 'updateReplication' init container parameters
## based on the *global.existingSecret/*containerSecurityContext parameters
##
updateReplication:
  ## Init container's resource requests and limits
  ## ref: https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
  ## @param volumePermissions.resources.limits The resources limits for the init container
  ## @param volumePermissions.resources.requests The requested resources for the init container
  ##
  resources:
    ## Example:
    ## limits:
    ##   cpu: 500m
    ##   memory: 1Gi
    limits: {}
    requests: {}


## Configure extra options for liveness, readiness, and startup probes
## ref: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
livenessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 10
readinessProbe:
  enabled: true
  initialDelaySeconds: 20
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 10
startupProbe:
  enabled: true
  initialDelaySeconds: 0
  periodSeconds: 10
  timeoutSeconds: 1
  successThreshold: 1
  failureThreshold: 30

## test container details
test:
  enabled: false
  image:
    repository: dduportal/bats
    tag: 0.4.0

## ltb-passwd
# For more parameters check following file: ./charts/ltb-passwd/values.yaml
ltb-passwd:
  enabled : false
  image:
    repository: sealos.hub:5000/tiredofit/self-service-password
    tag: 5.2.3
  ingress:
    enabled: true
    annotations: {}
    # See https://kubernetes.io/docs/concepts/services-networking/ingress/#ingressclass-scope
    # ingressClassName: nginx
    path: /
    pathType: Prefix
    ## Ingress Host
    hosts:
    - "ssl-ldap2.example"
    ## Ingress cert
    tls: []
    # - secretName: ssl-ldap2.example
    #   hosts:
    #   - ssl-ldap2.example
  # ldap:
    # if you want to restrict search base tree for users instead of complete domain
    # searchBase: "ou=....,dc=mydomain,dc=com"
    # if you want to use a dedicated bindDN for the search with less permissions instead of cn=admin one
    # bindDN: "cn=....,dc=mydomain,dc=com"
    # if you want to use a specific key of the credentials secret instead of the default one (LDAP_ADMIN_PASSWORD)
    # passKey: LDAP_MY_KEY

## phpldapadmin
## For more parameters check following file: ./charts/phpldapadmin/values.yaml
phpldapadmin:
  enabled: false
  image:
    tag: 0.9.0
  env:
    PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
  ingress:
    enabled: true
    annotations: {}
    ## See https://kubernetes.io/docs/concepts/services-networking/ingress/#ingressclass-scope
    # ingressClassName: nginx
    path: /
    pathType: Prefix
    ## Ingress Host
    hosts:
    - phpldapadmin.example
    ## Ingress cert
    tls: []
    # - secretName: phpldapadmin.example
    #   hosts:
    #   - phpldapadmin.example
  ```
2. Go to '....' or execute '...'
3. See error

**Expected behavior**

**Screenshots**

**Additional context**
