### ISSUE TITLE
findbase failed! 32

### ISSUE THREAD

**Issue by slapcat** [jp-gouin/helm-openldap#221]
**Describe the bug**
Replication fails due to `findbase failed! 32` error, but the base exists.

**Logs**
openldap-1:
```
6750d32e.2e6b562d 0x7fbdb63476c0 conn=1012 fd=21 TLS established tls_ssf=256 ssf=256 tls_proto=TLSv1.3 tls_cipher=TLS_AES_256_GCM_SHA384
6750d32e.2e7020af 0x7fbdb6b486c0 conn=1012 op=1 BIND dn="cn=admin,dc=nabasny,dc=com" method=128
6750d32e.2e713c44 0x7fbdb6b486c0 conn=1012 op=1 BIND dn="cn=admin,dc=nabasny,dc=com" mech=SIMPLE bind_ssf=0 ssf=256
6750d32e.2e730d36 0x7fbdb6b486c0 conn=1012 op=1 RESULT tag=97 err=0 qtime=0.000023 etime=0.000306 text=
6750d32e.2e7c134c 0x7fbdb5b466c0 conn=1012 op=2 SRCH base="dc=nabasny,dc=com" scope=2 deref=0 filter="(objectClass=*)"
6750d32e.2e7ce4b8 0x7fbdb5b466c0 conn=1012 op=2 SRCH attr=* +
6750d32e.2e7f153c 0x7fbdb5b466c0 findbase failed! 32
6750d32e.2e818314 0x7fbdb5b466c0 conn=1012 op=2 SEARCH RESULT tag=101 err=32 qtime=0.000024 etime=0.000419 nentries=0 text=
6750d32e.2e8dc448 0x7fbdb53456c0 conn=1012 op=3 UNBIND
```
openldap-0:
```
6750d31b.2e7e1c79 0x7f1439b166c0 do_syncrep2: rid=103 LDAP_RES_SEARCH_RESULT (32) No such object
6750d31b.2e7f5cf7 0x7f1439b166c0 do_syncrep2: rid=103 (32) No such object
6750d31b.2e833390 0x7f1439b166c0 do_syncrepl: rid=103 rc -101 retrying
```

**To Reproduce**

1. Use following values :
  ```yaml
global:
  ldapDomain: "nabasny.com"
  existingSecret: "openldap"
  adminUser: "admin"
  configUser: "admin"
  ldapPort: 389

image:
  repository: jpgouin/openldap
  tag: 2.6.8-fix

service:
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.0.243
  enableLdapPort: true
  enableSslLdapPort: false

env:
 BITNAMI_DEBUG: "true"
 LDAP_LOGLEVEL: "256"
 LDAP_REQUIRE_TLS: "false"
 LDAPTLS_REQCERT: "never"
 LDAP_ENABLE_TLS: "yes"
 LDAP_SKIP_DEFAULT_TREE: "yes"
 LDAP_ALLOW_ANON_BINDING: "no"
 LDAP_TLS_ENFORCE: "false"
 LDAP_TLS: "true"

replication:
  enabled: true
  clusterName: "cluster.local"
  retry: 60
  timeout: 1
  interval: 00:00:00:10
  starttls: "critical"

initTLSSecret:
  tls_enabled: true
  image:
    registry: docker.io
    repository: alpine/openssl
    tag: latest
    pullPolicy: IfNotPresent
  secret: "openldap-tls" 
  ```
2. Restore old database with base "dc=nabasny,dc=com":
```
kubectl cp /srv/backups/db-2024-12-04.ldif openldap-0:/tmp/
kubectl exec -it openldap-0 -- slapadd -n2 -F /bitnami/openldap/slapd.d/ -l /tmp/db-2024-12-04.ldif
```
4. openldap-0 will have all information and work well, but -1 and -2 never get the data replicated.

**Expected behavior**
LDAP entries from openldap-0 are replicated to secondary pods.

**Additional context**
I originally tried without TLS but had the same issue. I thought it might be due to not having TLS, so I set that up but got the same result.

**Comment by slapcat** [comment]
Preloading the base gets rid of the error, but replication still isn't happening.
```
customLdifFiles:
  00-root.ldif: |-
    # Root creation
    dn: dc=nabasny,dc=com
    objectClass: dcObject
    objectClass: organization
    o: Nabasny Family
```
