### ISSUE TITLE
Overwrite LDAP_EXTRA_SCHEMAS

### ISSUE THREAD

**Issue by tiborauer** [jp-gouin/helm-openldap#229]
**Is your feature request related to a problem? Please describe.**
I want to use the rfc2307bis schema instead of the predeployed nis one.

**Describe the solution you'd like**
I would like to overwrite the LDAP_EXTRA_SCHEMAS environmental variable.

**Describe alternatives you've considered**
- Specify LDAP_EXTRA_SCHEMAS  within [env](https://github.com/jp-gouin/helm-openldap/blob/3dc8ba18748f1fad4fb1e9f8e76ce075340398d6/values.yaml#L145) (preferred) - no effect
- Specify LDAP_EXTRA_SCHEMAS within [extraEnvVars   ](https://github.com/jp-gouin/helm-openldap/blob/3dc8ba18748f1fad4fb1e9f8e76ce075340398d6/values.yaml#L385) - no effect

**Comment by jp-gouin** [comment]
Hi @tiborauer ,

The base image is actually a fork of [Bitnami/openldap](https://github.com/bitnami/containers/tree/main/bitnami/openldap). You should check in the repo if what you want to do is doable. 
I've never tried to change a complete `rfc` scheme

**Comment by tiborauer** [comment]
Hi @jp-gouin ,

Thank you for your quick response!

I believe my suggestion doesn't concern the bitnami image. Please take a look at [my take on what I habe in mind](https://github.com/jp-gouin/helm-openldap/compare/master...reprostat:helm-openldap:master). I have not tested yet, so it may not be valid. I have never tried to write a helm repo.:⁠-⁠)

Btw, I managed to deploy your repo (with the original base schemes) with the current bitnami image (non-fix). I think they may have already merged your suggestion.

**Comment by tiborauer** [comment]
Just to clarify:
My workflow would be to omit 'nis' from the initial schemas and add rfc2307bis to the `customSchemaFiles`.

**Comment by jp-gouin** [comment]
alright 👍, would you like to submit a PR to expose the `initialSchema ` in the values files ?

Did you deployed the chart with multiple replica using the Bitnami image ?

**Comment by tiborauer** [comment]
I have just submitted a PR.

Yes, I have deployed 2 replicas.

**Comment by jp-gouin** [comment]
Thanks for the PR 

That’s weird my changes were reverted and are not in the upstream https://github.com/bitnami/containers/blob/a10465783d71b356ed13a5a462691ce1908f108a/bitnami/openldap/2.6/debian-12/rootfs/opt/bitnami/scripts/libopenldap.sh#L685 

The Tls is done after the custom Ldif. Due to the replication, the custom ldif for replicas openldap-1 , openldap-2 ,… breaks the initialisation because of a race condition between the init and the replication .

When it fails using the upstream container , the tls is not initialized and therefore it breaks . 

Maybe you’re not using custom ldif

**Comment by tiborauer** [comment]
It is strange, indeed, because I am using custom LDIFs. Anyway, you are fast enough to provide fixed versions ☺️, so I am happy to use them.

**Comment by tiborauer** [comment]
However, I am using only one replica (in addition to the main one. Maybe that is the answer.

**Comment by jp-gouin** [comment]
I'll do some more testing. If I can eventually drop the fixed version and rely on the upstream image that's better

**Comment by tiborauer** [comment]
Would you take care of the PR nevertheless?
It is unrelated to the image.

**Comment by davidfrickert** [comment]
@tiborauer can you maybe share what values.yaml snippet you use to enable rfc2307bis?

i've tried:

```
initialSchema: "cosine,inetorgperson,rfc2307bis"

customSchemaFiles:
  rfc2307bis.ldif: |-
    (... the entire rfc2307bis ldif ...)
```

but this doesn't actually result in a clean bootstrap as the chart tries to place `rfc2307bis` again in the LDAP_EXTRA_SCHEMAS env var:

```
        - name: LDAP_EXTRA_SCHEMAS
          value: cosine,inetorgperson,rfc2307bis,acls,00-dynlist-load,01-dyngroup-schema,02-dynlist-cfg,rfc2307bis
```

this obviously causes a crash of the init process due to `rfc2307bis` being declared twice. i can't remove `rfc2307bis` from the `initialSchema` because it needs to be declared before `acls` which is auto added by the chart after `initialSchema` and before the custom schemas.

**Comment by davidfrickert** [comment]
perhaps the chart needs another values.yaml variable similar to `customSchemaFiles` but one that does not attempt to add automatically to `LDAP_EXTRA_SCHEMAS`, or am i missing something?

**Comment by tiborauer** [comment]
@davidfrickert, I am afraid the `customSchemaFiles` does not work here. I had to do a little trick:

1. I created a configmap for the schemas (sorry for the ansible snippet)

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: schema-initial
  namespace: openldap
data:
  rfc2307bis: "{{ lookup('file','files/rfc2307bis.ldif') }}"
```

2. I mounted the configmap, so that the custom schemas are already added to the pre-loaded schemas:

``` yaml
initialSchema: "cosine,inetorgperson,rfc2307bis"
    extraVolumeMounts:
      - name: initial-schema
        subPath: rfc2307bis.ldif
        mountPath: /opt/bitnami/openldap/etc/schema/rfc2307bis.ldif
    extraVolumes:
      - name: initial-schema
        configMap:
          name: schema-initial
          items:
            - key: rfc2307bis
              path: rfc2307bis.ldif
```
