### ISSUE TITLE
TLS to ldap seems to be enforced in the chart

### ISSUE THREAD

**Issue by flixman** [jp-gouin/helm-openldap#235]
**Describe the bug**
I am trying to get phpldapadmin to communicate without TLS to openldap. With a clean installation of the chart, the custom value for the variable PHPLDAPADMIN_LDAP_HOSTS is ignored.

**To Reproduce**
Install the helm chart with the following custom values:

```
phpldapadmin:
  enabled: true
  ingress: 
    enabled: true
    hosts:
      - phpldapadmin.test.local
  env:
    PHPLDAPADMIN_LDAP_HOSTS: "#PYTHON2BASH:[{ 'openldap.openldap'  : [{'server': [{'tls': False},{'port':389}]},{'login': [{'bind_id': 'cn=openldap,dc=test,dc=local}]}]}]"
```

**Expected behavior**
The config map for phpldapadmin is updated with the correct value.
