### ISSUE TITLE
Adding customLdifFiles in TLS mode results in dhparam.pem error

### ISSUE THREAD

**Issue by kgibcc** [jp-gouin/helm-openldap#27]
adding custom ldif results in container error:
```
chmod: cannot access '/container/service/slapd/assets/certs/dhparam.pem': No such file or directory
***  ERROR  | 2021-05-07 00:22:57 | /container/run/startup/slapd failed with status 1

***  INFO   | 2021-05-07 00:22:57 | Killing all processes...
```
pod spawns correctly without any custom ldif

yaml is
```
# Custom openldap configuration files used to override default settings
customLdifFiles:
  app.ldif: |-
    dn: cn=app-user,dc=app,dc=dev,dc=example,dc=net
    userPassword: app-user-secret
    description: user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: app
```

**Comment by jp-gouin** [comment]
Hi,

Could you share your `values.yaml`? 

This is what i use in my test : 

```
# settings for enabling TLS with custom certificate
customTLS:
  enabled: true
  secret: "custom-certs"
customLdifFiles:
  01-default-group.ldif: |-
    dn: cn=myGroup,dc=example,dc=org
    cn: myGroup
    gidnumber: 500
    objectclass: posixGroup
    objectclass: top
  02-default-user.ldif: |-
    dn: cn=Jean Dupond,dc=example,dc=org
    cn: Jean Dupond
    gidnumber: 500
    givenname: Jean
    homedirectory: /home/users/jdupond
    objectclass: inetOrgPerson
    objectclass: posixAccount
    objectclass: top
    sn: Dupond
    uid: jdupond
    uidnumber: 1000
    userpassword: {MD5}KOULhzfBhPTq9k7a9XfCGw==
```

**Comment by kgibcc** [comment]
I'm still having issue with custom ldifs.

Yaml defined as:

```
customLdifFiles:
  kafka.ldif: |-
    dn: cn=kafka,dc=kafka,dc=dev,dc=example,dc=net
    userPassword: kafka-secret
    description: user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: kafka
  erp.ldif: |-
    dn: cn=erp,dc=kafka,dc=dev,dc=example,dc=net
    userPassword: erp-secret
    description: erp user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: erp
  sr.ldif: |-
    dn: cn=sr,dc=kafka,dc=dev,dc=example,dc=net
    userPassword: sr-secret
    description: schema registry user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: sr
  c3.ldif: |-
    dn: cn=c3,dc=kafka,dc=dev,dc=example,dc=net
    userPassword: c3-secret
    description: control center user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: c3
  ksql.ldif: |-
    dn: cn=ksql,dc=kafka,dc=dev,dc=example,dc=net
    userPassword: ksql-secret
    description: ksql user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: ksql
  connect.ldif: |-
    dn: cn=connect,dc=kafka,dc=dev,dc=example,dc=net
    userPassword: connect-secret
    description: connect user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: connect
  replicator.ldif: |-
    dn: cn=replicator,dc=kafka,dc=dev,dc=example,dc=net
    userPassword: replicator-secret
    description: replicator user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: replicator
  c3-test.ldif: |-
    dn: cn=c3,dc=kafka,dc=dev,dc=example,dc=net
    userPassword: testadmin
    description: testadmin user
    objectClass: simpleSecurityObject
    objectClass: organizationalRole
    cn: testadmin
```
That seems to work fine in getting the ldif files into the container:

```
root@openldap-0:/# cd /container/service/slapd/assets/config/bootstrap/ldif/custom/
root@openldap-0:/container/service/slapd/assets/config/bootstrap/ldif/custom# ls
c3.ldif  c3-test.ldif  connect.ldif  erp.ldif  kafka.ldif  ksql.ldif  replicator.ldif  sr.ldif
root@openldap-0:/container/service/slapd/assets/config/bootstrap/ldif/custom# cat sr.ldif
dn: cn=sr,dc=kafka,dc=dev,dc=cardinalaws,dc=net
userPassword: sr-secret
description: schema registry user
objectClass: simpleSecurityObject
objectClass: organizationalRole
```
and then the ldif files apply successfully 
```
cn: kafkaroot@openldap-0:/container/service/slapd/assets/config/bootstrap/ldif/custom# ldapadd -H ldap://openldap.openldap.svc.cluster.local:389 -D "cn=admin,dc=kafka,dc=dev,dc=example,dc=net" -w 'adminpassword' -f /container/service/slapd/assets/config/bootstrap/ldif/custom/sr.ldif
adding new entry "cn=sr,dc=kafka,dc=dev,dc=example,dc=net"
```
but then after a few minutes, the ldif entry is removed.

These are logs in debug mode before the entry is deleted
```
60a58a60 conn=1005 op=16962 SEARCH RESULT tag=101 err=0 nentries=0 text=
60a58a60 conn=1005 op=16963 SRCH base="dc=kafka,dc=dev,dc=exmple,dc=net" scope=1 deref=3 filter="(&(objectClass=organizationalRole)(objectClass=organizationalRole)(cn=sr))"
60a58a60 conn=1005 op=16963 SRCH attr=cn
60a58a60 <= mdb_equality_candidates: (cn) not indexed
60a58a60 conn=1005 op=16963 SEARCH RESULT tag=101 err=0 nentries=0 text=
60a58a60 conn=1006 op=11506 SRCH base="dc=kafka,dc=dev,dc=example,dc=net" scope=1 deref=3 filter="(&(objectClass=organizationalRole)(objectClass=organizationalRole)(cn=sr))"
60a58a60 conn=1006 op=11506 SRCH attr=cn
60a58a60 <= mdb_equality_candidates: (cn) not indexed
60a58a60 conn=1006 op=11506 SEARCH RESULT tag=101 err=0 nentries=0 text=
60a58a60 conn=1006 op=11507 SRCH base="dc=kafka,dc=dev,dc=example,dc=net" scope=1 deref=3 filter="(&(objectClass=organizationalRole)(objectClass=organizationalRole)(cn=kafka))"
60a58a60 conn=1006 op=11507 SRCH attr=cn
60a58a60 <= mdb_equality_candidates: (cn) not indexed
60a58a60 conn=1006 op=11507 SEARCH RESULT tag=101 err=0 nentries=0 text=
60a58a60 conn=1005 op=16964 SRCH base="dc=kafka,dc=dev,dc=example,dc=net" scope=1 deref=3 filter="(&(objectClass=organizationalRole)(objectClass=organizationalRole)(cn=sr))"
60a58a60 conn=1005 op=16964 SRCH attr=cn
60a58a60 <= mdb_equality_candidates: (cn) not indexed
60a58a60 conn=1005 op=16964 SEARCH RESULT tag=101 err=0 nentries=0 text=
```

Could you please provide some insight into what may be happening?  I'm not sure why some ldif's stick while others fall away.  I'm also not sure why they all don't apply on deploy and need to be manually implemented.
