### ISSUE TITLE
Affinity missing

### ISSUE THREAD

**Issue by riba2101** [jp-gouin/helm-openldap#39]
Hi,

is there a reason why affinity is missing/is not configurable?

BR

**Comment by jp-gouin** [comment]
Hello @riba2101 

`affinity` is configured in the `statefullset` 
```yaml
affinity: 
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: {{ template "openldap.fullname" . }}
                release: {{ .Release.Name }}
```

It could be great to be able to configure this in the values.

would you like to submit a PR ?
