### ISSUE TITLE
Trying to inject an olcAccess rule

### ISSUE THREAD

**Issue by melnik13** [jp-gouin/helm-openldap#58]
Hello,

Is that possible to add an `olcAccess` rule as in the `customLdifFiles` section?

Here's my `customLdifFiles` parameter of the Helm values configuration (simplified):
```
customLdifFiles:
  02-t.example.com.ldif: |-
    version: 1

    dn: dc=t,dc=example,dc=com
    associateddomain: t.example.com
    dc: t
    objectclass: dNSDomain
    objectclass: domainRelatedObject
    objectclass: top

  03-infra.t.example.com.ldif: |-
    version: 1

    dn: dc=infra,dc=t,dc=example,dc=com
    associateddomain: infra.t.example.com
    dc: infra
    objectclass: dNSDomain
    objectclass: domainRelatedObject
    objectclass: top

  99-access_rules.ldif: |-
    version: 1

    dn: olcdatabase={1}mdb,cn=config
    changetype: modify
    add: olcaccess
    olcaccess: to dn.subtree="dc=infra,dc=t,dc=example,dc=com" by dn.exact="uid=admin,dc=infra,dc=t,dc=example,dc=com" manage by dn.exact="uid=odmin,dc=infra,dc=t,dc=example,dc=com" read
```

As I can see, `02-t.example.com.ldif` and `03-infra.t.example.com.ldif` get applied without any difficulties, but `99-access_rules.ldif` doesn't.

When the container starts, I exec bash (`kubectl exec ...`) and I see this file in the `/container/service/slapd/assets/config/bootstrap/ldif/custom` directory. Moreover, I can apply it manually (`ldapadd -H ldapi:/// -Y EXTERNAL < /container/service/slapd/assets/config/bootstrap/ldif/custom/99-access_rules.ldif`).

Why doesn't it being applied during the initialization process?

Thanks in advance.
