### ISSUE TITLE
Pod "openldap-0" is invalid: [spec.volumes[1].secret.secretName: Required value, spec.initContainers[0].volumeMounts[1].name: Not found: "secret-certs"

### ISSUE THREAD

**Issue by Ramshield** [jp-gouin/helm-openldap#60]
**Describe the bug**
Error in stateful set:
```
create Pod openldap-0 in StatefulSet openldap failed error: Pod "openldap-0" is invalid: [spec.volumes[1].secret.secretName: Required value, spec.initContainers[0].volumeMounts[1].name: Not found: "secret-certs"]
```

Any suggestions what I'm doing wrong, or if something in the helm Chart is wrong? :) Thank you!

**To Reproduce**
1. `helm repo add helm-openldap https://jp-gouin.github.io/helm-openldap/`
2. Create `values-openldap.yaml`
```
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: "fast-disks"
  ldapDomain: "test.local
```
3. `helm install openldap helm-openldap/openldap-stack-ha -f values-openldap.yaml`

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubunt 20.04
- Kubernetes version:
```
$  kubectl version
Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:49:13Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.6", GitCommit:"ad3338546da947756e8a88aa6822e9c11e7eac22", GitTreeState:"clean", BuildDate:"2022-04-14T08:43:11Z", GoVersion:"go1.17.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Additional context**

**Comment by jp-gouin** [comment]
Hi , 

`customTLS` is enabled by default in the values.
It should be default to **false** , i'll update the chart but in the meantime you can deploy the chart using : 
 ```
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: "fast-disks"
  ldapDomain: "test.local
customTLS:
  enabled: false
```
