### ISSUE TITLE
ERROR  | 2022-05-30 16:25:56 | /container/run/startup/slapd failed with status 80

### ISSUE THREAD

**Issue by panhaitao** [jp-gouin/helm-openldap#63]
**Describe the bug**

**To Reproduce**
1. 使用自定义域名
2. 部署在EKS中使用helm部署
3. 使用免费DN证书
4. openldap-0                               0/1     CrashLoopBackOff   6          12m
5. ERROR  | 2022-05-30 16:25:56 | /container/run/startup/slapd failed with status 80

**配置**

openldap-vaules.yaml
```
global:
  storageClass: "gp2"
  ldapDomain: onwalk.net
  adminPassword: {{ ExtraVars.password }}
  configPassword: {{ ExtraVars.password }}
replicaCount: 1
customTLS:
  enabled: true
  secret: "openldap-tls" # 包含ca的pem 和key
ltb-passwd:
  ingress:
    enabled: true
    hosts:
    - "ldap-ltb.onwalk.net"
phpldapadmin:
  enabled: true
  ingress:
    enabled: true
    hosts:
    - ldap-admin.onwalk.net
 env:
    PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: "never"
```
