### ISSUE TITLE
LDAP_CONFIG_ADMIN_ENABLED duplicated, causing yaml unmarshalling errors.

### ISSUE THREAD

**Issue by Northcode** [jp-gouin/helm-openldap#85]
**Describe the bug**
Commit af2c860ba910015ea18e0824a265fb802afaed8a, introduced a bug where LDAP_CONFIG_ADMIN_ENABLED is defined both in the configmap-env template, and the values.yaml file, which gets inserted into the template, causing duplicate key errors when deploying:
`Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors: line 28: mapping key "LDAP_CONFIG_ADMIN_ENABLED" already defined at line 22`

**To Reproduce**
Install the chart without specifying anything in values.env

You probably want to remove it from the configmap-env template, or only have it in the template if it is not defined in values.

**Comment by jp-gouin** [comment]
Hey @Northcode , could you check out v4.0.1 , I deleted the key in the CM

**Comment by Northcode** [comment]
It seems to deploy now. But after upgrading my base domain has changed to dc=example,dc=org and all my objects are gone. 
Keeping the same PVCs.
Reverting to 3.0.2 again restored all my ldap-data.
Is there some change to the way initialization is done in 4? I'm not using customLdifFiles.
My values (passwords stripped):
```
customTLS:
  enabled: false
global:
  adminPassword: <PASS>
  configPassword: <PASS>
  imagePullSecrets: []
  ldapDomain: northcode.no
  ldapPort: 389 # reset port to 389 to avoid breaking other services
  storageClass: local-path
image:
  repository: registry.local/northcode/ldap # custom build of oxixia image with password policy olc added
  tag: latest
phpldapadmin:
  enabled: true
  env:
    PHPLDAPADMIN_LDAP_CLIENT_TLS_REQCERT: never
  ingress:
    enabled: true
    hosts:
    - phpldapadmin.int.northcode.no
    path: /
ltb-passwd:
  enabled: true
  ingress:
    enabled: true
    host: "ldap-pass.int.northcode.no"
replicaCount: 2
service:
  externalTrafficPolicy: Local
  type: LoadBalancer
persistence:
  enabled: true
  storageClass: openebs-zfspv
  size: 4Gi
```
